version: "3.9"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: user_service_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynet

  app:
    build: .
    depends_on:
      - postgres
    networks:
      - mynet

volumes:
  pgdata:

networks:
  mynet:
